package com.axon.input;

import android.animation.Animator;
import android.animation.AnimatorListenerAdapter;
import android.animation.TimeInterpolator;
import android.animation.ValueAnimator;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;
import android.os.SystemClock;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;

import java.util.ArrayDeque;

/** Live preview / created control for the super-custom key display editor. */
final class SuperCustomControlView extends FrameLayout {
    /**
     * Custom centre-fill animation only. Android/OEM RippleDrawable and pressed backgrounds are not
     * used. The visual is a single opaque press-colour circle whose radius only grows.
     */
    private static final TimeInterpolator CENTRE_FILL_EASE = KeyAppearance::centreFillCurve;

    private final Handler handler = new Handler(Looper.getMainLooper());
    private final ArrayDeque<Long> cpsSamples = new ArrayDeque<>();
    private final LinearLayout content;
    private final TextView label;
    private final TextView cps;

    private final Paint surfacePaint = new Paint(Paint.ANTI_ALIAS_FLAG);
    private final Paint ripplePaint = new Paint(Paint.ANTI_ALIAS_FLAG);
    private final RectF keyBounds = new RectF();
    private final Path keyClipPath = new Path();

    private SuperCustomControlSpec spec;
    private boolean keyPressed;
    private boolean interactivePreview;
    private int idleColor;

    private ValueAnimator rippleAnimator;
    private float rippleProgress;
    private long ripplePressStartedMs;
    private long rippleFillEndsAtMs;
    private int rippleGeneration;

    private final Runnable rippleReset = () -> {
        if (keyPressed) return;
        rippleProgress = 0f;
        invalidate();
    };

    private final Runnable cpsRefresh = new Runnable() {
        @Override public void run() {
            refreshCps();
            if (!cpsSamples.isEmpty()) handler.postDelayed(this, 120L);
        }
    };

    SuperCustomControlView(Context context) {
        super(context);

        // Fully opt out of Android/OEM press visuals.  The key surface and the centre-fill circle
        // are both rendered below in onDraw().
        setBackground(null);
        setForeground(null);
        setStateListAnimator(null);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            setDefaultFocusHighlightEnabled(false);
        }
        setSoundEffectsEnabled(false);
        setHapticFeedbackEnabled(false);
        setClickable(false);
        setLongClickable(false);
        setFocusable(false);
        setFocusableInTouchMode(false);
        setDuplicateParentStateEnabled(false);
        setWillNotDraw(false);
        setClipToOutline(false);
        setClipChildren(false);

        content = new LinearLayout(context);
        content.setOrientation(LinearLayout.VERTICAL);
        content.setGravity(Gravity.CENTER);
        content.setBackground(null);
        content.setClickable(false);
        content.setFocusable(false);
        addView(content, new FrameLayout.LayoutParams(
                LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT));

        label = new TextView(context);
        label.setGravity(Gravity.CENTER);
        label.setIncludeFontPadding(false);
        label.setSingleLine(true);
        label.setBackground(null);
        label.setClickable(false);
        label.setFocusable(false);
        content.addView(label, new LinearLayout.LayoutParams(
                LayoutParams.MATCH_PARENT, 0, 1f));

        cps = new TextView(context);
        cps.setGravity(Gravity.CENTER);
        cps.setIncludeFontPadding(false);
        cps.setSingleLine(true);
        cps.setTextSize(10f);
        cps.setBackground(null);
        cps.setClickable(false);
        cps.setFocusable(false);
        content.addView(cps, new LinearLayout.LayoutParams(
                LayoutParams.MATCH_PARENT, LayoutParams.WRAP_CONTENT));

        // Preview touch is consumed here so no click/pressed state can be generated by View itself.
        setOnTouchListener((v, event) -> {
            if (!interactivePreview) return false;
            switch (event.getActionMasked()) {
                case MotionEvent.ACTION_DOWN:
                    setPressedState(true);
                    return true;
                case MotionEvent.ACTION_UP:
                case MotionEvent.ACTION_CANCEL:
                    setPressedState(false);
                    return true;
                default:
                    return true;
            }
        });
    }

    void setInteractivePreview(boolean enabled) {
        interactivePreview = enabled;
    }

    TextView labelView() {
        return label;
    }

    TextView cpsView() {
        return cps;
    }

    void applySpec(SuperCustomControlSpec next) {
        spec = next;
        if (next == null) return;

        idleColor = UiPalette.controlSurface(getContext());
        FrameLayout.LayoutParams lp = (FrameLayout.LayoutParams) getLayoutParams();
        if (lp == null) lp = new FrameLayout.LayoutParams(dp(next.widthDp), dp(next.heightDp));
        lp.width = dp(next.widthDp);
        lp.height = dp(next.heightDp);
        setLayoutParams(lp);

        // Ripple mode is rendered pixel-for-pixel in Canvas; no View alpha animation is allowed.
        setAlpha(next.motionMode == OverlayState.MOTION_RIPPLE ? 1f : next.opacityPercent / 100f);
        setScaleX(1f);
        setScaleY(1f);

        label.setText(next.labelText == null ? "" : next.labelText);
        label.setTextColor(next.textColor);
        label.setTextSize(next.textSizeSp);
        cps.setTextColor(next.textColor);
        cps.setTextSize(Math.max(9f, next.textSizeSp * 0.56f));
        cps.setVisibility(next.cpsEnabled ? View.VISIBLE : View.GONE);
        setPadding(dp(8), dp(6), dp(8), dp(6));

        if (next.motionMode != OverlayState.MOTION_RIPPLE) {
            cancelRippleAnimator();
            handler.removeCallbacks(rippleReset);
            rippleProgress = 0f;
        }

        refreshCps();
        invalidate();
    }

    void onBoundKeyEvent(boolean down) {
        if (down && !keyPressed) {
            long now = SystemClock.uptimeMillis();
            cpsSamples.addLast(now);
            handler.removeCallbacks(cpsRefresh);
            handler.post(cpsRefresh);
        }
        setPressedState(down);
    }

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        drawKeySurface(canvas);
        drawCenterFillCircle(canvas);
    }

    @Override
    protected void onDetachedFromWindow() {
        cancelRippleAnimator();
        handler.removeCallbacks(rippleReset);
        handler.removeCallbacks(cpsRefresh);
        super.onDetachedFromWindow();
    }

    private void setPressedState(boolean pressed) {
        if (spec == null || keyPressed == pressed) return;
        keyPressed = pressed;
        animate().cancel();

        final float baseAlpha = spec.opacityPercent / 100f;
        switch (spec.motionMode) {
            case OverlayState.MOTION_ALPHA:
                animate().alpha(pressed ? Math.max(0.22f, baseAlpha * 0.55f) : baseAlpha)
                        .setDuration(pressed ? 90L : 130L)
                        .start();
                break;

            case OverlayState.MOTION_RIPPLE:
                // One-way centre fill. Releasing never contracts the circle back to the centre.
                setAlpha(1f);
                setScaleX(1f);
                setScaleY(1f);
                if (pressed) {
                    startAdaptiveCentreFill(SystemClock.uptimeMillis());
                } else {
                    finishCentreFillAfterRelease(SystemClock.uptimeMillis());
                }
                break;

            case OverlayState.MOTION_NONE:
                cancelRippleAnimator();
                rippleProgress = 0f;
                setAlpha(baseAlpha);
                setScaleX(1f);
                setScaleY(1f);
                break;

            case OverlayState.MOTION_SIZE:
            default:
                cancelRippleAnimator();
                rippleProgress = 0f;
                animate().scaleX(pressed ? 0.965f : 1f)
                        .scaleY(pressed ? 0.965f : 1f)
                        .alpha(baseAlpha)
                        .setDuration(pressed ? 90L : 135L)
                        .start();
                break;
        }
        invalidate();
    }

    private void startAdaptiveCentreFill(long now) {
        handler.removeCallbacks(rippleReset);
        rippleGeneration++;
        ripplePressStartedMs = now;
        rippleProgress = 0f;
        long duration = KeyAppearance.nextCentreFillDuration(now);
        rippleFillEndsAtMs = now + duration;
        animateRippleTo(1f, duration, null);
    }

    private void finishCentreFillAfterRelease(long now) {
        handler.removeCallbacks(rippleReset);
        // Do not cancel/restart the fill on release: changing interpolators mid-flight was the main
        // source of the old mechanical feel. The same curve keeps its velocity to the edge.
        long remaining = Math.max(0L, rippleFillEndsAtMs - now);
        handler.postDelayed(rippleReset, remaining + 72L);
    }

    private void animateRippleTo(float target, long duration, Runnable endAction) {
        float end = clamp01(target);
        float start = clamp01(rippleProgress);
        int generation = ++rippleGeneration;

        cancelRippleAnimator();

        float distance = Math.abs(end - start);
        if (distance < 0.0001f) {
            rippleProgress = end;
            invalidate();
            if (endAction != null) endAction.run();
            return;
        }

        rippleAnimator = ValueAnimator.ofFloat(start, end);
        rippleAnimator.setDuration(Math.max(1L, duration));
        rippleAnimator.setInterpolator(CENTRE_FILL_EASE);
        rippleAnimator.addUpdateListener(animation -> {
            rippleProgress = (float) animation.getAnimatedValue();
            postInvalidateOnAnimation();
        });
        rippleAnimator.addListener(new AnimatorListenerAdapter() {
            private boolean cancelled;

            @Override public void onAnimationCancel(Animator animation) {
                cancelled = true;
            }

            @Override public void onAnimationEnd(Animator animation) {
                if (!cancelled && generation == rippleGeneration && endAction != null) {
                    endAction.run();
                }
            }
        });
        rippleAnimator.start();
    }

    private void drawKeySurface(Canvas canvas) {
        if (spec == null || getWidth() <= 0 || getHeight() <= 0) return;

        keyBounds.set(0f, 0f, getWidth(), getHeight());
        float corner = resolvedCornerRadius();

        int color = idleColor;
        if (spec.motionMode != OverlayState.MOTION_RIPPLE && keyPressed) {
            color = spec.pressColor;
        }

        surfacePaint.reset();
        surfacePaint.setAntiAlias(true);
        surfacePaint.setStyle(Paint.Style.FILL);
        surfacePaint.setColor(color);

        // Preserve the user's explicit opacity setting only.  The animation itself never changes it.
        int sourceAlpha = Color.alpha(color);
        surfacePaint.setAlpha(Math.round(sourceAlpha * spec.opacityPercent / 100f));
        canvas.drawRoundRect(keyBounds, corner, corner, surfacePaint);
    }

    private void drawCenterFillCircle(Canvas canvas) {
        if (spec == null || spec.motionMode != OverlayState.MOTION_RIPPLE) return;
        if (rippleProgress <= 0f || getWidth() <= 0 || getHeight() <= 0) return;

        keyBounds.set(0f, 0f, getWidth(), getHeight());
        float corner = resolvedCornerRadius();
        float halfW = keyBounds.width() * 0.5f;
        float halfH = keyBounds.height() * 0.5f;

        // Exactly the minimum radius required for a centre circle to reach the farthest key corner.
        // It stops here; it never overshoots beyond the amount needed to fill the key.
        float maxRadius = (float) Math.hypot(halfW, halfH);
        float radius = maxRadius * clamp01(rippleProgress);
        if (radius <= 0f) return;

        keyClipPath.reset();
        keyClipPath.addRoundRect(keyBounds, corner, corner, Path.Direction.CW);

        int save = canvas.save();
        canvas.clipPath(keyClipPath);

        ripplePaint.reset();
        ripplePaint.setAntiAlias(true);
        ripplePaint.setStyle(Paint.Style.FILL);
        // Exact configured press color.  No theme ripple tint, shader, blend, fade or alpha pulse.
        ripplePaint.setColor(spec.pressColor);
        canvas.drawCircle(keyBounds.centerX(), keyBounds.centerY(), radius, ripplePaint);

        canvas.restoreToCount(save);
    }

    private float resolvedCornerRadius() {
        return Math.max(0f, Math.min(dp(spec.cornerDp),
                Math.min(keyBounds.width(), keyBounds.height()) * 0.5f));
    }

    private void cancelRippleAnimator() {
        if (rippleAnimator != null) {
            rippleAnimator.cancel();
            rippleAnimator = null;
        }
    }

    private void refreshCps() {
        long cutoff = SystemClock.uptimeMillis() - 1000L;
        while (!cpsSamples.isEmpty() && cpsSamples.peekFirst() < cutoff) {
            cpsSamples.removeFirst();
        }
        if (spec == null || !spec.cpsEnabled) {
            cps.setText("");
            return;
        }
        cps.setText(spec.renderCps(cpsSamples.size()));
    }

    private static float clamp(float value, float min, float max) {
        return Math.max(min, Math.min(max, value));
    }

    private static float clamp01(float value) {
        if (value <= 0f) return 0f;
        if (value >= 1f) return 1f;
        return value;
    }

    private int dp(float value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }
}
